{% set name = "aionotify" %}
{% set version = "0.3.0" %}
{% set sha256 = "e4e5286a9c84a0b4b9e7f7a382589be196878382d6a3d34b3fcaa062cf4d428e" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  number: 0
  skip: true  # [not linux or py<34]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - aionotify

about:
  home: https://github.com/rbarrois/aionotify
  license: BSD-2-clause
  license_family: BSD
  license_file: LICENSE
  summary: Asyncio-powered inotify library
  doc_url: https://github.com/rbarrois/aionotify
  dev_url: https://github.com/rbarrois/aionotify

extra:
  recipe-maintainers:
    - hodgsonw
